version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: yamauthi-emulatorjs_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: lscr.io/linuxserver/emulatorjs:latest
    restart: on-failure
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    ports:
      - 3000:3000
      - 4001:4001 #optional
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage:/data