version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: yamauthi-yacht_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: "false"

  server:
    image: selfhostedpro/yacht
    restart: unless-stopped
    hostname: "${DEVICE_HOSTNAME}"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    ports:
      - 8000:8000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - /var/run/docker.sock:/var/run/docker.sock